using Mimari.Entity;
using Mimari.ORM;
using Mimari.ORM.Facade;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.IO;
using Microsoft.VisualBasic;
using System.Globalization;
using Zen.Barcode;
using System.Drawing.Printing;

namespace MarketOOP
{
    public partial class Form1 : Form
    {


        UrunlerORM uOrm = new UrunlerORM();
        Urunler urun = new Urunler();
        BirimTip bt = new BirimTip();
        FileStream filestream;
        BinaryReader binaryReader;
        byte[] resim;
        string resimyolu, tiklanan;
        int id;

        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            urunlerTableAdapter1.Fill(marketOOPDataSet1.Urunler);
        }
        enum Tiklanan
        {
            Ekle,
            Duzenle,
            Sil
        }

        void KdvHesapla(double oran)
        {
            
            try
            {
                kdv.Text = Math.Round(Convert.ToDouble(SatisFiyat.Text) * oran, 2).ToString();

                KDVORAN.Text = oran.ToString();
            }
            catch (Exception)
            {

                MessageBox.Show("SATIŞ FİYATINI DOĞRU GİRDİĞİNİZDEN EMİN OLUN");
            }
        }
     
  
        void SendParameters(string tiklanan)
        {
            try
            {
                if (resimyolu == null || resimyolu == string.Empty)
                    resim = null;

                urun.Id = id;
                urun.Barkod = Barkod.Text;
                urun.UrunAdi = UrunAdi.Text;
                urun.Kdv = Convert.ToDouble(kdv.Text);
                urun.KdvOrani = Convert.ToDouble(KDVORAN.Text);
                urun.StokMiktari = Convert.ToInt32(StokMiktar.Text);
                urun.Sinifi = Sınıfı.Text;
                urun.SonKullanmaTarihi = Convert.ToDateTime(SonKullTarih.Text);
                urun.Ozel_Kod1 = Convert.ToInt32(OzelKod1.Text);
                urun.Ozel_Kod2 = Convert.ToInt32(OzelKod2.Text);
                urun.SatisFiyat = Convert.ToDecimal(SatisFiyat.Text.Replace('.',','));
                urun.SatisFiyati_2 = Satis_Fiyat2.Value;
                urun.SatisFiyati_3 = SatisFiyat3.Value;
                urun.BirimAlisFiyati = Convert.ToDecimal(Birim_Alis_Fiyat.Text.Replace('.', ','));
                urun.Cinsi = Cins.Text;
                urun.KritikStokMiktari = Convert.ToInt32(KritikStokMiktar.Text);
                urun.KategoriID = (int)UrunKategorisi.SelectedValue;
                urun.BirimTipID = (int)BirimTip.SelectedValue;
                urun.TedarikciID = (int)Tedarikci.SelectedValue;
                urun.UrunResmi=resim;
                urun.BedenNo = Convert.ToInt16(BedenNo.Text);
                urun.Aktif = true;

                if (tiklanan == Tiklanan.Ekle.ToString())
                {
                    bool sonuc = uOrm.Insert(urun);

                    if (sonuc)
                    {
                        MessageBox.Show("kayıt eklendi");
                        dataGridView1.DataSource = uOrm.Select();
                    }
                }
      
                if (tiklanan == Tiklanan.Duzenle.ToString())
                {
                    bool sonuc = uOrm.Update(urun);

                    if (sonuc)
                    {
                        MessageBox.Show("Kayıt Güncellendi");
                        dataGridView1.DataSource = uOrm.Select();
                    }
                }
            }
            catch(Exception x)
            {
                MessageBox.Show("ZORUNLU ALANLARI DOLDURUN \n"+x.ToString());

            }
            
        }
        private void Form1_Load(object sender, EventArgs e)
        {
            
            dataGridView1.DataSource = uOrm.Select();
            int sayi = dataGridView1.Rows.Count;
            toolStripTextBox1.Text = "  " + sayi.ToString() + " ADET ÜRÜN LİSTELENMEKTE";
            TedarikciORM tOrm = new TedarikciORM();
            Tedarikci.DataSource = tOrm.Select();
            Tedarikci.ValueMember = "id";
            Tedarikci.DisplayMember = "SirketAdi";
            Tedarikci.SelectedIndex = -1;
            KategoriORM kOrm = new KategoriORM();
            UrunKategorisi.DataSource = kOrm.Select();
            UrunKategorisi.ValueMember = "id";
            UrunKategorisi.DisplayMember = "Adi";
            UrunKategorisi.SelectedIndex = -1;
            BirimTipleriORM bOrm = new BirimTipleriORM();
            BirimTip.DataSource=bOrm.Select();
            BirimTip.ValueMember = "id";
            BirimTip.DisplayMember = "Adi";
            BirimTip.SelectedIndex = -1;
            dataGridView1.DataSource=uOrm.Select();
            dataGridView1.Columns[3].DefaultCellStyle.Format = "c2";
            dataGridView1.Columns[2].DefaultCellStyle.Format = "c2";
            dataGridView1.Columns[4].DefaultCellStyle.Format = "c2";
            dataGridView1.Columns[6].DefaultCellStyle.Format = "c2";
            dataGridView1.Columns[7].DefaultCellStyle.Format = "c2";
            dataGridView1.Columns[8].DefaultCellStyle.Format = "c2";
            dataGridView1.Columns[6].DefaultCellStyle.FormatProvider = CultureInfo.GetCultureInfo("tr-TR");
            dataGridView1.Columns[8].DefaultCellStyle.FormatProvider = CultureInfo.GetCultureInfo("tr-TR");
            dataGridView1.Columns[7].DefaultCellStyle.FormatProvider = CultureInfo.GetCultureInfo("tr-TR");
            dataGridView1.Columns[2].DefaultCellStyle.FormatProvider = CultureInfo.GetCultureInfo("tr-TR");
            dataGridView1.Columns[3].DefaultCellStyle.FormatProvider = CultureInfo.GetCultureInfo("tr-TR");
            dataGridView1.Columns[4].DefaultCellStyle.FormatProvider = CultureInfo.GetCultureInfo("tr-TR");
        }

    
        private void button7_Click(object sender, EventArgs e)
        {
            openFileDialog1.Title = "Lutfen Resim Seçiniz";
            openFileDialog1.Filter = "Jpeg Dosyası(*.jpeg)|*.jpeg|Jpg Dosyası(*.jpg)|*.jpg|Gif Dosyası(*.gif)|*.gif|Png dosyası (*.png)|*.png";
            if (openFileDialog1.ShowDialog() == DialogResult.OK)
            {
              
                resimyolu = openFileDialog1.FileName;

            }
          
                if(resimyolu!=null)
                {
                    filestream = new FileStream(resimyolu, FileMode.Open, FileAccess.Read);

                    binaryReader = new BinaryReader(filestream);
                    resim = binaryReader.ReadBytes((int)filestream.Length);
                    binaryReader.Close();
                    filestream.Close();

                }
        }

        private void Yuzde8_Click(object sender, EventArgs e)
        {
            KdvHesapla(0.08);
        }

        private void yuzdebir_Click(object sender, EventArgs e)
        {
            KdvHesapla(0.01);
        }

        private void Yuzde18_Click(object sender, EventArgs e)
        {
            KdvHesapla(0.18);
        }

        private void toolStripButton5_Click(object sender, EventArgs e)
        {
            Btn_Ekle.Enabled = true;
            Btn_Sil.Enabled = true;
            Btn_Duzenle.Enabled = true;
            Btn_Kaydet.Enabled = false;
            Tools.FormTools.ClearAllText(panel2);
            panel2.Enabled = false;
        }

        private void Barkod_Validating(object sender, CancelEventArgs e)
        {
            if (Barkod.Text.Trim() == string.Empty)
            {
                errorProvider1.SetError(Barkod, "Barkod Bilgisini girin!");
            }
            else errorProvider1.SetError(Barkod, "");
        }

        private void UrunAdi_Validating(object sender, CancelEventArgs e)
        {
            if (UrunAdi.Text.Trim() == string.Empty)
            {
                errorProvider1.SetError(UrunAdi, "Ürün Adı Bilgisini Girin!");
            }
            else errorProvider1.SetError(UrunAdi, "");
        }

        private void Birim_Alis_Fiyat_Validating(object sender, CancelEventArgs e)
        {
            if (Birim_Alis_Fiyat.Text.Trim() == string.Empty)
            {
                errorProvider1.SetError(Birim_Alis_Fiyat, "Alış Fiyat Bilgisini Girin!");
            }
            else errorProvider1.SetError(Birim_Alis_Fiyat, "");
        }

        private void SatisFiyat_Validating(object sender, CancelEventArgs e)
        {
            if (SatisFiyat.Text.Trim() == string.Empty)
            {
                errorProvider1.SetError(SatisFiyat, "Satış Fiyat Bilgisini Girin!");
            }
            else errorProvider1.SetError(SatisFiyat, "");
        }

        private void StokMiktar_Validating(object sender, CancelEventArgs e)
        {
            if (StokMiktar.Text.Trim() == string.Empty)
            {
                errorProvider1.SetError(StokMiktar, " Stok Miktarını Girin!");
            }
            else errorProvider1.SetError(StokMiktar, "");
        }

        private void BirimTip_Validating(object sender, CancelEventArgs e)
        {
            if (BirimTip.Text.Trim() ==string.Empty)
            {
                errorProvider1.SetError(BirimTip, "Ürün Adı Bilgisini Girin!");
            }
            else errorProvider1.SetError(BirimTip, "");
        }

        private void StokGirisi_Click(object sender, EventArgs e)
        {
            Stok_Giris_Cikis stok_Giris = new Stok_Giris_Cikis();
            stok_Giris.Show();
        }

        private void StokCikis_Click(object sender, EventArgs e)
        {
            Stok_Giris_Cikis stok_Cikis = new Stok_Giris_Cikis();
            stok_Cikis.Show();
        }

        private void button2_Click(object sender, EventArgs e)
        {
            Tum_Urunler tum_Urunler = new Tum_Urunler();
     
            tum_Urunler.ShowDialog();
        }

        private void button3_Click(object sender, EventArgs e)
        {
            if(Barkod.Text==string.Empty)
            {
                MessageBox.Show("Lütfen Listeden Bir Ürün Seçiniz");

            }
            else
            {
                BarkodGenerator bg = new BarkodGenerator();
                double fiyattoplam = Convert.ToDouble(SatisFiyat.Text) + Convert.ToDouble(kdv.Text);
                bg.Barkod = Barkod.Text.Trim();
                bg.urunadi = UrunAdi.Text.Trim();
                bg.fiyat =fiyattoplam.ToString();
                bg.ShowDialog();
            }

        }
        KategoriEkle ktg = new KategoriEkle();
        
        private void yeniÜrünKategorisiEkleToolStripMenuItem_Click(object sender, EventArgs e)
        {

            if (ktg.IsDisposed)

                ktg = new KategoriEkle();
                ktg.Show();
        }
       
        private void yeniBirimTipToolStripMenuItem_Click(object sender, EventArgs e)
        {
            if (bt.IsDisposed)

                bt = new BirimTip();
                 bt.Show();
        }
        Tedarikci tedarikci = new Tedarikci();
        private void yeniTedarikçiToolStripMenuItem_Click(object sender, EventArgs e)
        {
            if (tedarikci.IsDisposed)
                tedarikci = new Tedarikci();
            tedarikci.Show();
        }
        Kasalar kasa = new Kasalar();
        private void yeniKasaToolStripMenuItem_Click(object sender, EventArgs e)
        {
            if (kasa.IsDisposed)
                kasa = new Kasalar();
            kasa.Show();
        }


        private void yeniÜrünEkleToolStripMenuItem_Click(object sender, EventArgs e)
        {
            KritikStokMiktari ksm = new KritikStokMiktari();
            ksm.ShowDialog();

        }

        private void dataGridView1_CellClick(object sender, DataGridViewCellEventArgs e)
        {
           
            id = (int)(dataGridView1.Rows[e.RowIndex].Cells["id"].Value);
            Barkod.Text = dataGridView1.Rows[e.RowIndex].Cells["Barkod"].Value.ToString();
            UrunAdi.Text = dataGridView1.Rows[e.RowIndex].Cells["UrunAdi"].Value.ToString();
            UrunKategorisi.Text = dataGridView1.Rows[e.RowIndex].Cells["Kategori"].Value.ToString();
            Tedarikci.Text = dataGridView1.Rows[e.RowIndex].Cells["Tedarikci"].Value.ToString();
            StokMiktar.Text = dataGridView1.Rows[e.RowIndex].Cells["StokMiktari"].Value.ToString();
            KritikStokMiktar.Text = dataGridView1.Rows[e.RowIndex].Cells["KritikStokMiktari"].Value.ToString();
            Sınıfı.Text = dataGridView1.Rows[e.RowIndex].Cells["Sinifi"].Value.ToString();
            BedenNo.Text = dataGridView1.Rows[e.RowIndex].Cells["BedenNo"].Value.ToString();
            kdv.Text = (Convert.ToDouble(dataGridView1.Rows[e.RowIndex].Cells["KDV"].Value)).ToString();
            Birim_Alis_Fiyat.Text = (Convert.ToDouble(dataGridView1.Rows[e.RowIndex].Cells["BirimAlisFiyati"].Value)).ToString();
            SatisFiyat.Text = (Convert.ToDouble(dataGridView1.Rows[e.RowIndex].Cells["SatisFiyat"].Value)).ToString();
            Satis_Fiyat2.Text = (Convert.ToDouble(dataGridView1.Rows[e.RowIndex].Cells["SatisFiyati_2"].Value)).ToString();
            SatisFiyat3.Text = (Convert.ToDouble(dataGridView1.Rows[e.RowIndex].Cells["SatisFiyati_3"].Value)).ToString();
            KDVORAN.Text = (Convert.ToDouble(dataGridView1.Rows[e.RowIndex].Cells["KdvOrani"].Value)).ToString();
            BirimTip.Text = dataGridView1.Rows[e.RowIndex].Cells["BirimTip"].Value.ToString();
            Cins.Text = dataGridView1.Rows[e.RowIndex].Cells["Cinsi"].Value.ToString();
            SonKullTarih.Text = dataGridView1.Rows[e.RowIndex].Cells["SonKullanmaTarihi"].Value.ToString();
            OzelKod1.Text = dataGridView1.Rows[e.RowIndex].Cells["Ozel_Kod1"].Value.ToString();
            OzelKod2.Text = dataGridView1.Rows[e.RowIndex].Cells["Ozel_Kod2"].Value.ToString();
        }

        private void Btn_Ekle_Click(object sender, EventArgs e)
        {
            panel2.Enabled = true;
            tiklanan = Tiklanan.Ekle.ToString();
            Tools.FormTools.ClearAllText(panel2);
            Btn_Sil.Enabled = false;
            Btn_Duzenle.Enabled = false;
            Btn_Kaydet.Enabled = true;
        }

        private void Btn_Duzenle_Click(object sender, EventArgs e)
        {
            if (Barkod.Text ==string.Empty)
            {
                MessageBox.Show("Ürün bilgilerini düzenlemek için listeden bir ürün seçiniz", "UYARI", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
            else
            {
                tiklanan = Tiklanan.Duzenle.ToString();
                panel2.Enabled = true;
                Btn_Ekle.Enabled = false;
                Btn_Sil.Enabled = false;
                Btn_Kaydet.Enabled = true;
            }
        }

        private void Btn_Kaydet_Click(object sender, EventArgs e)
        {
            DialogResult Soru = MessageBox.Show("DEĞİŞİKLİKLER KAYDEDİLSİN Mİ?", "UYARI", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
            if (Soru == DialogResult.Yes)
                SendParameters(tiklanan);
        }

        private void Btn_Sil_Click(object sender, EventArgs e)
        {
            try
            {
                tiklanan = Tiklanan.Sil.ToString();
                if (Barkod.Text == string.Empty)
                {
                    MessageBox.Show("Listeden silinecek ürünü seçiniz", "UYARI", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                }
                if (Barkod.Text !=string.Empty)
                {

                    panel2.Enabled = false;
                    Btn_Ekle.Enabled = true;
                    Btn_Duzenle.Enabled = true;
                    DialogResult Soru = MessageBox.Show("BU ÜRÜN SİLİNSİN Mİ?", "UYARI", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
                    if (Soru == DialogResult.Yes)
                    {
                        Urunler urunler = new Urunler();
                        urunler.Id = id;
                        bool sonuc = uOrm.Delete(urunler);
                        if (sonuc)
                        {
                            dataGridView1.DataSource = uOrm.Select();

                            Tools.FormTools.ClearAllText(panel2);
                        }
                    }
                }
            }
            catch (Exception x)
            {
                MessageBox.Show(x.ToString());
            }
        
        }

      
    }
}
